services:
  postgres:
    image: postgres:latest
    container_name: quest-room-api-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: quest-room-api-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: quest-room
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
